project:
  type: website
  output-dir: docs

website:
  title: "carte"
  navbar:
    left:
      - href: map.qmd
        text: map
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



